Version 7.1.0
input-output-hk/cardano-db-sync pull request #427
Opened 2020-12-08 09:40 UTC by erikd

2020-12-09 22:45 UTC, rhyslbw requested changes

2020-12-09 22:45 UTC, rhyslbw commented on docker-compose.yml
> +    image: inputoutput/cardano-node:1.24.1
`1.24.2`

2020-12-09 22:49 UTC, erikd commented on docker-compose.yml
> +    image: inputoutput/cardano-node:1.24.1
Fixed.

2020-12-10 08:41 UTC, ksaric commented
@erikd Can you please leave the commit `3cf868ec8c06265e4b670ac737af640d716e5ef7` separate and not rewrite Git history? For now, I'm depending on that commit and once you have things ready we can sync up and I can target your merge commit.

2020-12-10 09:09 UTC, erikd commented
If no further issues are found and this does indeed become the `7.1.0` release, this commit will remain. If an issue is found and it needs to be corrected, this commit will be replaced by the fix commit.

2020-12-10 09:12 UTC, ksaric commented
> If no further issues are found and this does indeed become the `7.1.0` release, this commit will remain. If an issue is found and it needs to be corrected, this commit will be replaced by the fix commit.

Yes, but could you just temporarily add a new commit and squash them when it's finalized?

2021-09-24 09:48 UTC, closed without merging