Fix Github Actions caching
input-output-hk/cardano-db-sync pull request #441
Opened 2020-12-15 03:06 UTC by newhoggy

2020-12-15 03:07 UTC, newhoggy commented on .github/workflows/haskell.yml
> +        path: dist
Caching the `dist` directory separately.

2020-12-22 03:32 UTC, erikd requested changes
JUst make sure the commit message does not line wrap and drop the trailing empty lines.

2020-12-22 03:32 UTC, erikd commented on Readme.md
> +
Can we drop these empty newlines?

2020-12-22 03:38 UTC, erikd approved these changes

2020-12-22 03:51 UTC, merged