[CAD-2895] Move the simple DBSyncPlugin as a separate plugin in db-sync
input-output-hk/cardano-db-sync pull request #601
Opened 2021-05-04 09:46 UTC by ksaric

https://jira.iohk.io/browse/CAD-2895

I have returned the schema back, while trying to do as few changes as possible, doing it with all those changes to the schema is next to impossible.

2021-05-06 01:02 UTC, erikd commented on cardano-db/src/Cardano/Db/Schema.hs
> +    hash                Types.PoolMetaHash        sqltype=text
No, the original types were correct.

2021-05-06 01:05 UTC, erikd commented on cardano-db/src/Cardano/Db/Schema.hs
> +
No, the existing `db-sync` already has tables that contain what you are putting in `Pool` and `RetiredPool`.

The tables are `PoolUpdate` and `PoolRetire`.

2021-05-06 01:06 UTC, erikd commented on cardano-db/src/Cardano/Db/Schema.hs
> +import           Cardano.Db.Schema.Types as Types
My understanding is that the tables required by SMASH have **already** been added and should probably not need to be changed.

2021-05-06 01:07 UTC, erikd requested changes
Change requests already submitted.

2021-05-06 09:24 UTC, ksaric commented
> I have returned the schema back, while trying to do as few changes as possible, doing it with all those changes to the schema is next to impossible.

Erik, I have already noted this. I tried to do this, but this requires a large number of changes and once I realized it's a rabbit hole that will take a huge amount of time, I switched back to the original SMASH schema.
I'm not saying this couldn't be better, but for now, _please_, let us merge this, and then you can modify this to your heart's content and shape it in any way you want.

2021-05-06 22:03 UTC, erikd commented
Sorry, I will not be merging this until its right, because if I do there is not guarantee that it will ever get fixed.  Blocking merge until it is fixed is the only to guarantee it is fixed.

2021-05-28 05:16 UTC, erikd commented
This has been superceded by #619 .

2021-05-28 05:16 UTC, closed without merging