[CAD-2913] Move the metadata fetch thread for re-fetching of the pools
input-output-hk/cardano-db-sync pull request #603
Opened 2021-05-05 12:51 UTC by ksaric

https://jira.iohk.io/browse/CAD-2913

Based on https://github.com/input-output-hk/cardano-db-sync/pull/601, requires that to be merged first.

2021-05-05 23:43 UTC, erikd requested changes

2021-05-05 23:43 UTC, erikd commented on cardano-db/src/Cardano/Db/Schema.hs
> +    hash                Types.PoolMetaHash        sqltype=text
No. This should not have been changed.

2021-05-06 09:24 UTC, ksaric commented
https://github.com/input-output-hk/cardano-db-sync/pull/601#issuecomment-833375928

2021-06-15 01:25 UTC, erikd commented
Not needed any more.

2021-06-15 01:25 UTC, closed without merging